/**
 * integration.test.ts — OpenClaw Evo full-pipeline integration tests
 *
 * Tests the complete evolution pipeline end-to-end using vitest.
 * External dependencies (gateway, filesystem) are mocked with vi.mock() / vi.stubGlobal().
 * Core classes (Evaluator, Builder, Comparator, MemoryStore) use real instances with an
 * isolated tmpdir memory store per test suite.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import type {
  SessionMetrics,
  Experiment,
  GeneratedSkill,
  FailurePattern,
  ExperimentResult,
  HubState,
} from '../src/types.js';

// ── Import real implementations ─────────────────────────────────────────────────

import { scoreSessions } from '../src/evaluator/scorer.js';
import { detectPatterns } from '../src/evaluator/patternDetector.js';
import { generateFromFailure } from '../src/builder/skillGenerator.js';
import { validate } from '../src/builder/skillValidator.js';
import { comparator } from '../src/experiment/comparator.js';
import { promoter } from '../src/experiment/promoter.js';
import { MemoryStore } from '../src/memory/store.js';

// ── Mocked external dependencies ────────────────────────────────────────────────

// Mock SkillManager.installSkill to write to a temp directory instead of ~/.openclaw/skills/
const TEST_SKILLS_DIR = join(process.cwd(), '.test-skills-output');

vi.mock('../src/openclaw/skillManager.js', () => ({
  SkillManager: vi.fn().mockImplementation(() => ({
    installSkill: vi.fn(async (skill: GeneratedSkill) => {
      const dir = join(TEST_SKILLS_DIR, skill.id);
      await mkdir(dir, { recursive: true });
      await writeFile(join(dir, 'SKILL.md'), `# ${skill.name}\n\n${skill.implementation}`, 'utf-8');
      await writeFile(join(dir, 'skill.json'), JSON.stringify({ name: skill.name }), 'utf-8');
      await writeFile(join(dir, 'meta.json'), JSON.stringify(skill), 'utf-8');
      return dir;
    }),
    listInstalledSkills: vi.fn().mockResolvedValue([]),
    uninstallSkill: vi.fn().mockResolvedValue(undefined),
  })),
}));

// Mock Gateway fetch — return deterministic mock session data so experiment runner can complete
vi.stubGlobal(
  'fetch',
  vi.fn(async (url: string) => {
    const urlStr = String(url);

    // POST /api/sessions → return a mock session ID
    if (urlStr.match(/\/api\/sessions$/) && !urlStr.includes('?')) {
      return { ok: true, json: () => Promise.resolve({ sessionId: `mock-session-${Date.now()}` }) } as Response;
    }

    // GET /api/sessions/:id → return completed session immediately
    if (urlStr.match(/\/api\/sessions\/[^/]+$/)) {
      return {
        ok: true,
        json: () =>
          Promise.resolve({
            sessionId: urlStr.split('/').pop(),
            status: 'completed',
            success: true,
            toolCalls: [],
            startTime: Date.now() - 5000,
            endTime: Date.now(),
          }),
      } as Response;
    }

    // GET /api/skills/:id → return mock skill content (used by loadTreatmentSkill in promote)
    if (urlStr.match(/\/api\/skills\/[^/]+$/)) {
      const skillId = urlStr.split('/').pop() ?? 'unknown';
      return {
        ok: true,
        json: () =>
          Promise.resolve({
            id: skillId,
            name: `Integration Test Skill`,
            description: 'Mock skill for integration testing — auto-generated by test mock gateway',
            triggerPhrases: ['integration test'],
            implementation:
              '// Mock skill implementation for integration testing.\n// This code is long enough to pass validation checks.\n' +
              `// Skill ID: ${skillId}\n` +
              'export async function handler(input: string) {\n  return { success: true, result: "mock" };\n}',
            examples: [{ input: 'test', expectedOutput: 'ok', explanation: 'mock test' }],
            confidence: 0.9,
            status: 'proposed',
            generatedAt: new Date().toISOString(),
          }),
      } as unknown as Response;
    }

    return { ok: false, status: 404 } as unknown as Response;
  }),
);

// ── Isolated MemoryStore factory ──────────────────────────────────────────────

function makeTempStore(): MemoryStore {
  return new MemoryStore(join(process.cwd(), '.test-memory', randomUUID()));
}

// ── Temp dir cleanup ─────────────────────────────────────────────────────────

async function cleanupTempDirs(): Promise<void> {
  await rm(join(process.cwd(), '.test-memory'), { recursive: true, force: true }).catch(() => {});
  await rm(TEST_SKILLS_DIR, { recursive: true, force: true }).catch(() => {});
}

// ── Reset promoter in-memory state between tests ───────────────────────────────

// No beforeEach needed — each test uses unique experiment/approval IDs.

afterEach(async () => {
  await cleanupTempDirs();
});

// ── Test helpers ──────────────────────────────────────────────────────────────

function makeFailedToolCall(overrides: Partial<import('../src/types.js').ToolCall> = {}): import('../src/types.js').ToolCall {
  return {
    id: randomUUID(),
    name: 'read',
    input: { path: '/etc/hosts' },
    output: undefined,
    error: 'Permission denied: /etc/hosts',
    startTime: Date.now() - 1000,
    endTime: Date.now(),
    success: false,
    ...overrides,
  };
}

function makeSession(overrides: Partial<SessionMetrics> = {}): SessionMetrics {
  return {
    sessionId: randomUUID(),
    toolCalls: [],
    startTime: Date.now() - 60_000,
    endTime: Date.now(),
    success: false,
    errorCount: 1,
    totalToolCalls: 1,
    avgLatencyMs: 500,
    taskType: 'file_read',
    ...overrides,
  };
}

/** Build an experiment with explicit result arrays that pass 95% confidence threshold. */
function makeWinningExperiment(skillId: string): Experiment {
  // 0/20 control vs 20/20 treatment → 100% improvement, z=5.16, p≈1.2e-7, confidence≈100%
  const controlResults: ExperimentResult[] = Array.from({ length: 20 }, (_, i) => ({
    taskId: `task-${i}`,
    success: false,  // 0/20 = 0%
    toolCalls: 3,
    durationMs: 5000,
    score: 0,
  }));

  const treatmentResults: ExperimentResult[] = Array.from({ length: 20 }, (_, i) => ({
    taskId: `task-${i}`,
    success: true,   // 20/20 = 100%
    toolCalls: 2,
    durationMs: 4000,
    score: 100,
  }));

  return {
    id: `exp-${randomUUID()}`,
    name: 'A/B: Test Skill',
    description: 'Integration test experiment',
    treatmentSkillId: skillId,
    controlSkillId: 'baseline',
    taskSet: [],
    status: 'completed',
    controlResults,
    treatmentResults,
    statisticalSignificance: 0,
    improvementPct: 0,
    startedAt: new Date(Date.now() - 60_000),
    completedAt: new Date(),
  };
}

// (injectApproval removed — use public API only; vi.resetModules() in beforeEach
// gives each test a fresh promoter with empty Maps.)

// ══════════════════════════════════════════════════════════════════════════════
// TEST GROUP 1 — Evolution pipeline
// ══════════════════════════════════════════════════════════════════════════════

describe('Evolution pipeline', () => {

  // ── 1A. scoreSessions ─────────────────────────────────────────────────────
  describe('scoreSessions', () => {
    it('returns a valid PerformanceScore for a batch of sessions', () => {
      const sessions: SessionMetrics[] = [
        makeSession({ success: true,  errorCount: 0, totalToolCalls: 3 }),
        makeSession({ success: true,  errorCount: 0, totalToolCalls: 4 }),
        makeSession({ success: false, errorCount: 1, totalToolCalls: 2 }),
      ];

      const score = scoreSessions(sessions);

      expect(score.overall).toBeGreaterThan(0);
      expect(score.overall).toBeLessThanOrEqual(100);
      expect(score.accuracy).toBeGreaterThan(0);
      // 2/3 sessions succeeded → accuracy ≈ 66.67
      expect(score.accuracy).toBeCloseTo(66.67, 0);
    });

    it('returns zero scores when no sessions are provided', () => {
      const score = scoreSessions([]);
      expect(score.overall).toBe(0);
      expect(score.accuracy).toBe(0);
    });

    it('awards max efficiency when tool calls equal the optimal count', () => {
      const sessions = [makeSession({ totalToolCalls: 3, success: true, errorCount: 0 })];
      const score = scoreSessions(sessions, 60_000, 3);  // optimalCalls = 3
      expect(score.efficiency).toBe(100);
    });
  });

  // ── 1B. detectPatterns ────────────────────────────────────────────────────
  describe('detectPatterns', () => {
    it('detects a repeating failure pattern across multiple sessions', () => {
      const failureCall = makeFailedToolCall({ name: 'read', error: 'Permission denied' });

      const sessions: SessionMetrics[] = [0, 1, 2].map((i) =>
        makeSession({
          sessionId: `s${i}`,
          toolCalls: [{ ...failureCall, id: `tc-${i}`, startTime: Date.now() + i * 1000 }],
          success: false,
          errorCount: 1,
          totalToolCalls: 1,
        }),
      );

      const patterns = detectPatterns(sessions);

      expect(patterns.length).toBeGreaterThan(0);
      const readPattern = patterns.find((p) => p.toolName === 'read');
      expect(readPattern).toBeDefined();
      expect(readPattern!.frequency).toBeGreaterThanOrEqual(3);
    });

    it('returns an empty array when no sessions contain failures', () => {
      const sessions = [makeSession({ success: true, errorCount: 0, toolCalls: [] })];
      expect(detectPatterns(sessions)).toHaveLength(0);
    });

    it('sorts patterns by frequency descending', () => {
      const highFreqCall = makeFailedToolCall({ name: 'http', error: 'Timeout' });
      const lowFreqCall  = makeFailedToolCall({ name: 'read', error: 'NotFound' });

      const sessions: SessionMetrics[] = [
        ...Array.from({ length: 5 }, (_, i) =>
          makeSession({
            sessionId: `high-${i}`,
            toolCalls: [{ ...highFreqCall, id: `h-${i}`, startTime: Date.now() + i }],
            success: false, errorCount: 1, totalToolCalls: 1,
          }),
        ),
        ...Array.from({ length: 2 }, (_, i) =>
          makeSession({
            sessionId: `low-${i}`,
            toolCalls: [{ ...lowFreqCall, id: `l-${i}`, startTime: Date.now() + 100 + i }],
            success: false, errorCount: 1, totalToolCalls: 1,
          }),
        ),
      ];

      const patterns = detectPatterns(sessions);
      expect(patterns[0].frequency).toBeGreaterThanOrEqual(patterns[1].frequency);
    });
  });

  // ── 1C. generateFromFailure ─────────────────────────────────────────────
  describe('generateFromFailure', () => {
    it('generates a valid skill from a failure pattern with high confidence', () => {
      const pattern: FailurePattern = {
        id: `fp-${randomUUID()}`,
        toolName: 'read',
        errorType: 'permission_error',
        errorMessage: 'Permission denied',
        frequency: 5,
        severity: 'high',
        exampleContexts: [
          {
            sessionId: 's1',
            taskDescription: 'Read /etc/hosts',
            toolInput: { path: '/etc/hosts' },
            errorOutput: 'Permission denied',
            timestamp: new Date(),
          },
        ],
        firstSeen: new Date(Date.now() - 86_400_000),
        lastSeen: new Date(),
        autoFixAvailable: false,
      };

      const result = generateFromFailure(pattern, { skipValidation: false });

      expect(result.skill).toBeDefined();
      expect(result.skill.name).toContain('read');
      expect(result.skill.status).toBe('proposed');
      expect(result.skill.confidence).toBeGreaterThan(0);
      expect(result.skill.implementation.length).toBeGreaterThan(100);
      expect(result.skill.triggerPhrases.length).toBeGreaterThan(0);
      expect(result.skill.targetFailurePattern).toBe(pattern.id);
    });

    it('generates a skill with skipValidation even when examples are missing', () => {
      const pattern: FailurePattern = {
        id: `fp-${randomUUID()}`,
        toolName: 'search',
        errorType: 'timeout',
        errorMessage: 'Request timed out',
        frequency: 1,
        severity: 'medium',
        exampleContexts: [],
        firstSeen: new Date(),
        lastSeen: new Date(),
        autoFixAvailable: false,
      };

      // Should not throw — validation is bypassed
      const result = generateFromFailure(pattern, { skipValidation: true });
      expect(result.skill.id).toBeTruthy();
    });

    it('throws when skipValidation is false and pattern produces a low-quality skill', () => {
      const pattern: FailurePattern = {
        id: `fp-${randomUUID()}`,
        toolName: 'unknown_tool',
        errorType: 'unknown',
        errorMessage: 'Something went wrong',
        frequency: 1,
        severity: 'low',
        exampleContexts: [],
        firstSeen: new Date(),
        lastSeen: new Date(),
        autoFixAvailable: false,
      };

      // Low frequency + no examples → low confidence + short implementation → validation fails
      expect(() => generateFromFailure(pattern)).toThrow();
    });

    it('generates distinct skill names for distinct failure patterns', () => {
      const patterns: FailurePattern[] = [
        {
          id: `fp-${randomUUID()}`, toolName: 'read', errorType: 'not_found',
          errorMessage: 'File does not exist', frequency: 3, severity: 'medium',
          exampleContexts: [], firstSeen: new Date(), lastSeen: new Date(),
          autoFixAvailable: false, suggestedFix: 'Check the file path before reading.',
        },
        {
          id: `fp-${randomUUID()}`, toolName: 'write', errorType: 'permission_error',
          errorMessage: 'Permission denied', frequency: 3, severity: 'high',
          exampleContexts: [], firstSeen: new Date(), lastSeen: new Date(),
          autoFixAvailable: false, suggestedFix: 'Grant write permissions to the target directory.',
        },
      ];

      const results = patterns.map((p) => generateFromFailure(p, { skipValidation: true }));
      const names = results.map((r) => r.skill.name);
      expect(new Set(names).size).toBe(names.length);
    });
  });

  // ── 1D. validate ──────────────────────────────────────────────────────────
  describe('validate', () => {
    it('returns valid=true for a well-formed skill from generateFromFailure', () => {
      const pattern: FailurePattern = {
        id: `fp-${randomUUID()}`,
        toolName: 'http',
        errorType: 'timeout',
        errorMessage: 'Request timed out',
        frequency: 5,
        severity: 'high',
        exampleContexts: [
          {
            sessionId: 's1',
            taskDescription: 'Fetch API data',
            toolInput: { url: 'https://example.com' },
            errorOutput: 'Timeout',
            timestamp: new Date(),
          },
        ],
        firstSeen: new Date(),
        lastSeen: new Date(),
        autoFixAvailable: false,
      };

      const { skill } = generateFromFailure(pattern);
      const result = validate(skill);

      expect(result.valid).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    it('returns errors for a skill missing a name', () => {
      const skill: GeneratedSkill = {
        id: randomUUID(),
        name: '',
        description: 'A test skill with a sufficiently long description',
        triggerPhrases: ['test phrase'],
        implementation: '// some code here that is definitely more than 100 chars to pass length checks.',
        examples: [{ input: 'test', expectedOutput: 'ok', explanation: 'test' }],
        confidence: 0.8,
        status: 'proposed',
        generatedAt: new Date(),
      };

      const result = validate(skill);
      expect(result.valid).toBe(false);
      expect(result.errors.some((e) => e.toLowerCase().includes('name'))).toBe(true);
    });

    it('returns errors for a skill with no trigger phrases', () => {
      const skill: GeneratedSkill = {
        id: randomUUID(),
        name: 'Test Skill',
        description: 'A test skill description that is long enough',
        triggerPhrases: [],
        implementation: '// some code here that is definitely more than 100 chars. this is enough content.',
        examples: [{ input: 'test', expectedOutput: 'ok', explanation: 'test' }],
        confidence: 0.5,
        status: 'proposed',
        generatedAt: new Date(),
      };

      const result = validate(skill);
      expect(result.valid).toBe(false);
      expect(result.errors.some((e) => e.toLowerCase().includes('trigger'))).toBe(true);
    });

    it('returns errors for a skill with unfilled template placeholders', () => {
      const skill: GeneratedSkill = {
        id: randomUUID(),
        name: 'Bad Skill',
        description: 'Has unfilled template markers',
        triggerPhrases: ['test trigger'],
        implementation: '// TODO: fill in {{TOOL_NAME}} and {{ERROR_TYPE}} placeholders',
        examples: [{ input: 'test', expectedOutput: 'ok', explanation: 'test' }],
        confidence: 0.5,
        status: 'proposed',
        generatedAt: new Date(),
      };

      const result = validate(skill);
      expect(result.valid).toBe(false);
      expect(result.errors.some((e) => e.includes('{{TOOL_NAME}}'))).toBe(true);
    });

    it('returns warnings for a skill with very short description', () => {
      const skill: GeneratedSkill = {
        id: randomUUID(),
        name: 'Short Desc Skill',
        description: 'Too short',
        triggerPhrases: ['test trigger'],
        implementation: '// some code here that is definitely more than 100 chars. this is enough content.',
        examples: [{ input: 'test', expectedOutput: 'ok', explanation: 'test' }],
        confidence: 0.5,
        status: 'proposed',
        generatedAt: new Date(),
      };

      const result = validate(skill);
      expect(result.warnings.some((w) => w.toLowerCase().includes('short'))).toBe(true);
    });
  });

  // ── 1E. promoter.evaluate ─────────────────────────────────────────────────
  describe('promoter.evaluate', () => {
    it('recommends promotion when treatment significantly outperforms control', () => {
      const skillId = `skill-${randomUUID()}`;
      const experiment = makeWinningExperiment(skillId);

      promoter.register(experiment);
      const decision = promoter.evaluate(experiment);

      // 6/10 vs 9/10 should produce statistically significant improvement
      expect(decision.promoted).toBe(true);
      expect(decision.experimentsValidated).toBeGreaterThan(0);
    });

    it('rejects promotion when improvement is below threshold', () => {
      // Both arms have identical results → 0% improvement
      const makeResults = (successes: number): ExperimentResult[] =>
        Array.from({ length: 10 }, (_, i) => ({
          taskId: `task-${i}`,
          success: i < successes,
          toolCalls: 3,
          durationMs: 5000,
          score: i < successes ? 80 : 0,
        }));

      const experiment: Experiment = {
        id: `exp-${randomUUID()}`,
        name: 'No-Gain Experiment',
        description: 'No improvement over baseline',
        treatmentSkillId: `skill-${randomUUID()}`,
        controlSkillId: 'baseline',
        taskSet: [],
        status: 'completed',
        controlResults: makeResults(5),
        treatmentResults: makeResults(5),  // identical → 0% improvement
        statisticalSignificance: 0,
        improvementPct: 0,
        startedAt: new Date(),
        completedAt: new Date(),
      };

      promoter.register(experiment);
      const decision = promoter.evaluate(experiment);

      expect(decision.promoted).toBe(false);
      expect(decision.reason.toLowerCase()).toMatch(/improvement|threshold|not met/);
    });

    it('rejects a pending experiment immediately', () => {
      const experiment: Experiment = {
        id: `exp-${randomUUID()}`,
        name: 'Pending experiment',
        description: 'Not started yet',
        treatmentSkillId: `skill-${randomUUID()}`,
        taskSet: [],
        status: 'pending',
        controlResults: [],
        treatmentResults: [],
        statisticalSignificance: 0,
        improvementPct: 0,
        startedAt: new Date(),
      };

      promoter.register(experiment);
      const decision = promoter.evaluate(experiment);

      expect(decision.promoted).toBe(false);
      expect(decision.reason.toLowerCase()).toMatch(/pending|running|status/);
    });

    it('returns already-promoted for an experiment with promotedAt set', () => {
      const experiment: Experiment = {
        id: `exp-${randomUUID()}`,
        name: 'Already promoted',
        description: 'Was promoted previously',
        treatmentSkillId: `skill-${randomUUID()}`,
        taskSet: [],
        status: 'completed',
        controlResults: [],
        treatmentResults: [],
        statisticalSignificance: 0.99,
        improvementPct: 20,
        startedAt: new Date(),
        completedAt: new Date(),
        promotedAt: new Date(),
      };

      promoter.register(experiment);
      const decision = promoter.evaluate(experiment);

      expect(decision.promoted).toBe(true);
      expect(decision.reason.toLowerCase()).toMatch(/already|previous/);
    });

    it('returns error decision for an unknown experiment ID', () => {
      const decision = promoter.evaluate('nonexistent-experiment-id');
      expect(decision.promoted).toBe(false);
      expect(decision.reason.toLowerCase()).toMatch(/not found/i);
    });

    it('isSignificant helper returns true above threshold', () => {
      const skillId = `skill-${randomUUID()}`;
      const experiment = makeWinningExperiment(skillId);
      promoter.register(experiment);

      const statResult = comparator.compare(experiment);
      expect(comparator.isSignificant(statResult, 0.95)).toBe(true);
    });
  });
});

// ══════════════════════════════════════════════════════════════════════════════
// TEST GROUP 2 — Hub checkpoint / resume via MemoryStore
// ══════════════════════════════════════════════════════════════════════════════

describe('Hub checkpoint and resume', () => {
  it('persists hub state to MemoryStore and restores it on a new instance', async () => {
    // Use the same store dir for both save and restore (simulates real Hub lifecycle
    // where EvoHub saves a checkpoint then creates a new instance and calls resume())
    const store = makeTempStore();
    await store.init();

    const proposedSkills: GeneratedSkill[] = [
      {
        id: `skill-${randomUUID()}`,
        name: 'Read Permission Fix',
        description: 'Handles permission errors for read operations',
        triggerPhrases: ['read permission error'],
        implementation: '// skill implementation placeholder text here to meet length requirements',
        examples: [{ input: 'read /etc/shadow', expectedOutput: 'ok', explanation: 'ok' }],
        confidence: 0.75,
        status: 'proposed',
        generatedAt: new Date(),
        targetFailurePattern: 'fp-1',
      },
    ];

    const state: HubState = {
      cycleNumber: 5,
      completedCycles: [],
      proposedSkills,
      activeExperiments: [],
      lastCheckpoint: new Date(),
    };

    // Save checkpoint
    await store.save('hub-state', state);

    // Verify file was written
    const keys = await store.list();
    expect(keys).toContain('hub-state');

    // Restore on a new store instance using the same directory
    const restored: HubState | null = await store.load<HubState>('hub-state');

    expect(restored).not.toBeNull();
    expect(restored!.cycleNumber).toBe(5);
    expect(restored!.proposedSkills).toHaveLength(1);
    expect(restored!.proposedSkills[0].name).toBe('Read Permission Fix');
    expect(restored!.lastCheckpoint).toBeDefined();
  });

  it('overwrites an existing checkpoint on re-save', async () => {
    const store = makeTempStore();
    await store.init();

    const state1: HubState = { cycleNumber: 1, completedCycles: [], proposedSkills: [], activeExperiments: [], lastCheckpoint: new Date() };
    const state2: HubState = { cycleNumber: 2, completedCycles: [], proposedSkills: [], activeExperiments: [], lastCheckpoint: new Date() };

    await store.save('hub-state', state1);
    await store.save('hub-state', state2);

    const restored = await store.load<HubState>('hub-state');
    expect(restored!.cycleNumber).toBe(2);
  });

  it('estimateSize returns a non-negative number', async () => {
    const store = makeTempStore();
    await store.init();
    expect(store.estimateSize()).toBeGreaterThanOrEqual(0);
  });

  it('getMemoryDir returns the configured directory path', async () => {
    const store = makeTempStore();
    expect(store.getMemoryDir()).toContain('.test-memory');
  });
});

// ══════════════════════════════════════════════════════════════════════════════
// TEST GROUP 3 — MemoryStore roundtrip
// ══════════════════════════════════════════════════════════════════════════════

describe('MemoryStore roundtrip', () => {
  it('saves and loads a complex nested object', async () => {
    const store = makeTempStore();
    await store.init();

    const payload = {
      scores: { accuracy: 80, efficiency: 65, speed: 90, reliability: 75, coverage: 50, overall: 72 },
      patterns: [
        {
          id: 'fp-1',
          toolName: 'read',
          errorType: 'not_found',
          errorMessage: 'File not found',
          frequency: 10,
          severity: 'high' as const,
          exampleContexts: [],
          firstSeen: new Date().toISOString(),
          lastSeen: new Date().toISOString(),
          autoFixAvailable: true,
          suggestedFix: 'Check path before reading',
        },
      ],
    };

    await store.save('test-roundtrip', payload);
    const loaded = await store.load<typeof payload>('test-roundtrip');

    expect(loaded).not.toBeNull();
    expect(loaded!.scores.overall).toBe(72);
    expect(loaded!.patterns[0].toolName).toBe('read');
  });

  it('load returns null for a non-existent key', async () => {
    const store = makeTempStore();
    await store.init();
    expect(await store.load('non-existent-key-xyz')).toBeNull();
  });

  it('list() returns all saved keys', async () => {
    const store = makeTempStore();
    await store.init();

    await store.save('key-a', { value: 1 });
    await store.save('key-b', { value: 2 });
    await store.save('key-c', { value: 3 });

    const keys = await store.list();
    expect(keys.sort()).toEqual(['key-a', 'key-b', 'key-c']);
  });

  it('delete removes the key and load returns null', async () => {
    const store = makeTempStore();
    await store.init();

    await store.save('to-delete', { data: 'test' });
    expect(await store.load('to-delete')).not.toBeNull();

    await store.delete('to-delete');
    expect(await store.load('to-delete')).toBeNull();
  });

  it('save overwrites an existing key with new data', async () => {
    const store = makeTempStore();
    await store.init();

    await store.save('counter', { count: 10 });
    await store.save('counter', { count: 99 });

    const loaded = await store.load<{ count: number }>('counter');
    expect(loaded!.count).toBe(99);
  });
});

// ══════════════════════════════════════════════════════════════════════════════
// TEST GROUP 4 — Approval workflow: promote → approveSkill → deployed
// ══════════════════════════════════════════════════════════════════════════════

describe('Approval workflow', () => {
  it('promote() returns requires_approval with an approvalId without deploying', async () => {
    const skillId = `skill-${randomUUID()}`;
    const experiment = makeWinningExperiment(skillId);

    promoter.register(experiment);

    const result = await promoter.promote(experiment.id);

    expect(result.promoted).toBe(false);
    expect(result.reason).toBe('requires_approval');
    expect(result.approvalId).toBeDefined();
    expect(result.approvalId).toMatch(/^approval-/);

    // Skill should NOT be written to the skills dir yet
    const skillFile = join(TEST_SKILLS_DIR, skillId, 'SKILL.md');
    await expect(readFile(skillFile, 'utf-8')).rejects.toThrow();
  });

  it('getPendingApprovals() returns skills awaiting approval', async () => {
    const skillId = `skill-${randomUUID()}`;
    const experiment = makeWinningExperiment(skillId);

    promoter.register(experiment);
    await promoter.promote(experiment.id);

    const pending = promoter.getPendingApprovals();
    expect(pending.some((a) => a.skillId === skillId && a.status === 'pending')).toBe(true);
  });

  it('approveSkill() deploys the skill and updates approval status to approved', async () => {
    const skillId = `skill-${randomUUID()}`;
    const experiment = makeWinningExperiment(skillId);

    promoter.register(experiment);
    const { approvalId } = await promoter.promote(experiment.id);
    expect(approvalId).toBeDefined();

    await promoter.approveSkill(approvalId!);

    // Approval should no longer be in the pending list
    const pending = promoter.getPendingApprovals();
    expect(pending.find((a) => a.skillId === skillId && a.status === 'pending')).toBeUndefined();

    // Skill file should be written to the mocked skills dir
    const skillFile = join(TEST_SKILLS_DIR, skillId, 'SKILL.md');
    const content = await readFile(skillFile, 'utf-8');
    expect(content).toContain(experiment.name.replace('A/B: ', ''));
  });

  it('approveSkill() throws for a non-existent approvalId', async () => {
    await expect(promoter.approveSkill('this-approval-does-not-exist')).rejects.toThrow(
      /approval not found/i,
    );
  });

  it('approveSkill() throws when the approval is already approved', async () => {
    const skillId = `skill-${randomUUID()}`;
    const experiment = makeWinningExperiment(skillId);

    promoter.register(experiment);
    const { approvalId } = await promoter.promote(experiment.id);

    // First approve — succeeds
    await promoter.approveSkill(approvalId!);

    // Second approve — throws
    await expect(promoter.approveSkill(approvalId!)).rejects.toThrow(/already/i);
  });

  it('approveSkill() deploys the skill and updates approval status to approved', async () => {
    // Use a winning experiment (0/20 vs 20/20 → 100% confidence)
    const skillId = `skill-${randomUUID()}`;
    const experiment = makeWinningExperiment(skillId);
    promoter.register(experiment);

    // promote() creates a pending approval (requires_approval flow)
    const { approvalId } = await promoter.promote(experiment.id);
    expect(approvalId).toBeDefined();
    expect(typeof approvalId).toBe('string');

    // Approve it — should not throw
    await promoter.approveSkill(approvalId!);

    // Skill file should be written to the mocked skills dir
    const skillFile = join(TEST_SKILLS_DIR, skillId, 'SKILL.md');
    const content = await readFile(skillFile, 'utf-8');
    expect(content).toContain(experiment.name.replace('A/B: ', ''));
  });

  it('rejectSkill() throws when approval is not found', () => {
    expect(() => promoter.rejectSkill('nonexistent-approval-id')).toThrow(/approval not found/i);
  });

  it('promote() throws for an unknown experiment ID', async () => {
    await expect(promoter.promote('unknown-experiment-id')).rejects.toThrow(
      /experiment not found/i,
    );
  });

  it('promote() is idempotent — returns already promoted without writing files twice', async () => {
    const skillId = `skill-${randomUUID()}`;
    const experiment: Experiment = {
      id: `exp-${randomUUID()}`,
      name: 'Idempotent Test',
      description: 'Testing idempotency',
      treatmentSkillId: skillId,
      taskSet: [],
      status: 'completed',
      controlResults: [],
      treatmentResults: [],
      statisticalSignificance: 0.99,
      improvementPct: 20,
      startedAt: new Date(),
      completedAt: new Date(),
      promotedAt: new Date(),  // Already marked as promoted
    };

    promoter.register(experiment);

    const result = await promoter.promote(experiment.id);

    expect(result.promoted).toBe(true);
    expect(result.reason.toLowerCase()).toMatch(/already/i);
  });
});
