/**
 * OpenClaw Evo — Skill Manager
 *
 * Manages OpenClaw skill files (installation, uninstallation, backup).
 */

import { readFile, writeFile, mkdir, readdir, copyFile, rm } from 'fs/promises';
import { join, dirname } from 'path';
import type { GeneratedSkill } from '../types.js';

export class SkillManager {
  private skillsDir: string;

  constructor(skillsDir = '~/.openclaw/skills/') {
    this.skillsDir = skillsDir.replace('~', process.env.HOME || '');
  }

  async listInstalledSkills(): Promise<string[]> {
    try {
      const entries = await readdir(this.skillsDir, { withFileTypes: true });
      return entries.filter((e) => e.isDirectory() || e.name.endsWith('.md')).map((e) => e.name);
    } catch {
      return [];
    }
  }

  async installSkill(skill: GeneratedSkill, experimentId?: string): Promise<string> {
    const dir = join(this.skillsDir, skill.id);
    await mkdir(dir, { recursive: true });

    const skillContent = [
      `# ${skill.name}`,
      '',
      `> ${skill.description}`,
      '',
      `## Triggers`,
      skill.triggerPhrases.map((t) => `- "${t}"`).join('\n'),
      '',
      `## Implementation`,
      '',
      skill.implementation,
      '',
      `---`,
      `* Generated by OpenClaw Evo on ${new Date().toISOString()}*`,
    ].join('\n');

    await writeFile(join(dir, 'SKILL.md'), skillContent, 'utf-8');

    const manifest = {
      name: skill.name,
      version: '1.0.0',
      description: skill.description,
      triggerPhrases: skill.triggerPhrases,
      generatedAt: skill.generatedAt instanceof Date ? skill.generatedAt.toISOString() : skill.generatedAt,
      experimentId,
    };
    await writeFile(join(dir, 'skill.json'), JSON.stringify(manifest, null, 2), 'utf-8');
    await writeFile(join(dir, 'meta.json'), JSON.stringify(skill, null, 2), 'utf-8');
    return dir;
  }

  async uninstallSkill(skillName: string): Promise<void> {
    const dir = join(this.skillsDir, skillName);
    await rm(dir, { recursive: true, force: true });
  }

  async backupSkill(skillName: string): Promise<string> {
    const src = join(this.skillsDir, skillName);
    const backupDir = join(this.skillsDir, '.backup', skillName);
    await mkdir(dirname(backupDir), { recursive: true });
    // Simple: just copy meta.json to backup
    try {
      const meta = await readFile(join(src, 'meta.json'), 'utf-8');
      await mkdir(backupDir, { recursive: true });
      await writeFile(join(backupDir, 'meta.json'), meta, 'utf-8');
    } catch {
      // ignore
    }
    return backupDir;
  }
}
